---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Manage real server pool
      fadcos_real_server_pool:
        action: edit
        name: rs_pool
        iptype: ipv6
        vdom: root
        healthcheck: enable
        health_check_list:
                - LB_HLTHCK_ICMP
                - LB_HLTHCK_HTTPS
