---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: edit
      fadcos_system_time_ntp:
       action: edit
       ntpserver: pool.ntp.org
       ntpsync: enable
       syncinterval: '60'

    - name: get
      fadcos_system_time_ntp:
       action: get

