---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Manage route satatic
      fadcos_route_static:
       action: add
       route_id: abc
       desination: 66.1.1.0/24
       gateway: 66.1.1.254
       distance: 10
       vdom: root
