- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add waf_api_gateway_policy
      fadcos_waf_api_gateway_policy:
        action: add
        name: test_gp1

    - name: get waf_api_gateway_policy
      fadcos_waf_api_gateway_policy:
        action: get
        name: test_gp1

    - name: delete waf_api_gateway_policy
      fadcos_waf_api_gateway_policy:
        action: delete
        name: test_gp1