- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add waf_api_discovery
      fadcos_waf_api_discovery:
        action: add
        name: ad1
        api_discovery: enable

    - name: edit waf_api_discovery
      fadcos_waf_api_discovery:
        action: edit
        name: ad1
        api_discovery: enable

    - name: get waf_api_discovery
      fadcos_waf_api_discovery:
        action: get
        name: ad1

    - name: delete waf_api_discovery
      fadcos_waf_api_discovery:
        action: delete
        name: ad1