- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add allowed_origin
      fadcos_waf_allowed_origin:
        action: add
        name: test_aw

    - name: get allowed_origin
      fadcos_waf_allowed_origin:
        action: get
        name: test_aw     

    - name: delete allowed_origin
      fadcos_waf_allowed_origin:
        action: delete
        name: test_aw