- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add cors_headers
      fadcos_waf_cors_headers:
        action: add
        name: test_cor

    - name: get cors_headers
      fadcos_waf_cors_headers:
        action: get
        name: test_cor    

    - name: delete cors_headers
      fadcos_waf_cors_headers:
        action: delete
        name: test_cor