- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add credential_stuffing_defense
      fadcos_waf_credential_stuffing_defense:
        action: add
        name: bsd1
        security_action: alert
        severity: medium
        status: enable

    - name: edit credential_stuffing_defense
      fadcos_waf_credential_stuffing_defense:
        action: edit
        name: bsd1
        security_action: block
        severity: low

    - name: get credential_stuffing_defense
      fadcos_waf_credential_stuffing_defense:
        action: get
        name: bsd1

    - name: delete credential_stuffing_defense
      fadcos_waf_credential_stuffing_defense:
        action: delete
        name: csd1