---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Manage Health Checks
      fadcos_health_check:
        action: add
        name: test_hc
        dest_addr_type: ipv4
        dest_addr: 1.2.3.5
        up_retry: 1
        down_retry: 3
        interval: 5
        timeout: 3
        hc_type: icmp
