---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:

    - name: get
      fadcos_system_time_ntp:
       action: get

    - name: edit
      fadcos_system_time_ntp:
       action: edit
       ntpsync: enable
       syncinterval: '40'
       

    - name: get
      fadcos_system_time_ntp:
       action: get

