---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: edit
      vars:
       ansible_command_timeout: 60
      fadcos_system_ha:
       mgmt_interface: 
       local_node_id: 0
       peer_address: 0.0.0.0
       group_name: 1
       sync_l4_persistent: disable
       monitor_enable: disable
       hbdev: port5
       mgmt_ip_allowaccess: 
       config_priority: 100
       hb_lost_threshold: 6
       isSystemAdmin: True
       override: disable
       groupid: 0
       node_list: 0 
       local_address: 0.0.0.0
       isSystemWritable: True
       mgmt_ip: 0.0.0.0/0
       sync_l4_connection: disable
       datadev: port2
       arp_num: 5
       failover_hold_time: 120
       interval: 2
       arp_interval: 6
       mode: active-passive
       mgmt_status: disable
       interface_list: port2
       sync_l7_persistent: disable
       hbtype: multicast
       failover_threshold: 5
       priority: 1
