---
- name:
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Manage Client SSL Profile
      fadcos_client_ssl_profile:
        action: add
        name: test_client_ssl_profile
